FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
ARG VITE_APP_TITLE="Ocotillo"
ARG VITE_BASE_URL="/"
ARG VITE_AUTHENTIK_CLIENT_ID
ARG VITE_AUTHENTIK_URL
ARG VITE_AUTHENTIK_REDIRECT_URI
ARG VITE_OCOTILLO_API_URL
ARG VITE_MAPBOX_TOKEN
ARG VITE_PUBLIC_POSTHOG_KEY
ARG VITE_PUBLIC_POSTHOG_HOST
ARG VITE_TEST_AUTH=true

ENV VITE_APP_TITLE=$VITE_APP_TITLE
ENV VITE_BASE_URL=$VITE_BASE_URL
ENV VITE_AUTHENTIK_CLIENT_ID=$VITE_AUTHENTIK_CLIENT_ID
ENV VITE_AUTHENTIK_URL=$VITE_AUTHENTIK_URL
ENV VITE_AUTHENTIK_REDIRECT_URI=$VITE_AUTHENTIK_REDIRECT_URI
ENV VITE_OCOTILLO_API_URL=$VITE_OCOTILLO_API_URL
ENV VITE_MAPBOX_TOKEN=$VITE_MAPBOX_TOKEN
ENV VITE_PUBLIC_POSTHOG_KEY=$VITE_PUBLIC_POSTHOG_KEY
ENV VITE_PUBLIC_POSTHOG_HOST=$VITE_PUBLIC_POSTHOG_HOST
ENV VITE_TEST_AUTH=$VITE_TEST_AUTH

RUN npm run build:ci

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
