import { DevtoolsProvider, DevtoolsPanel } from "@refinedev/devtools";
import {
  Refine,
  Authenticated,
} from "@refinedev/core";
import {
  ErrorComponent,
  RefineThemes,
  useNotificationProvider,
  RefineSnackbarProvider,
  AuthPage, Title,
} from "@refinedev/mui";
import CssBaseline from "@mui/material/CssBaseline";
import GlobalStyles from "@mui/material/GlobalStyles";
import FormControlLabel from "@mui/material/FormControlLabel";
import Checkbox from "@mui/material/Checkbox";
import { ThemeProvider } from "@mui/material/styles";
// import dataProvider from "@refinedev/simple-rest";
import routerProvider, {
  NavigateToResource,
  CatchAllNavigate,
  UnsavedChangesNotifier,
  DocumentTitleHandler,
} from "@refinedev/react-router-v6";
import {BrowserRouter, Routes, Route, Outlet, useNavigate, useLocation} from "react-router-dom";
import { useFormContext } from "react-hook-form";
import GitHubIcon from "@mui/icons-material/GitHub";
import GoogleIcon from "@mui/icons-material/Google";

import { dataProvider } from "./providers/data-provider";
import {authProvider} from "./providers/fief-provider";

import { LocationCreate, LocationEdit, LocationList } from "./pages/locations";
import { WellEdit, WellList } from "./pages/wells";

import { ThemedLayoutV2 } from "./components/layout";
import { ThemedHeaderV2 } from "./components/layout/header";
import { ThemedSiderV2 } from "./components/layout/sider";
import { ThemedTitleV2 } from "./components/layout/title";
import {useEffect} from "react";
import {FiefAuthProvider, useFiefAuth} from "@fief/fief/react";

import {LookupTableList} from "./components/lookuptable";

import {resources} from "./resources";
import {ColorModeContextProvider} from "./contexts";
/**
 *  mock auth credentials to simulate authentication
 */
const authCredentials = {
  email: "demo@refine.dev",
  password: "demodemo",
};

const App: React.FC = () => {
  const customTitleHandler = ({ resource, action,params,pathname, autoGeneratedTitle }) => {
    let title = 'NMBGMR Data Manager';
    // let
    if (action==="list") {
      title = `${resource.label} | ${title}`;
    }
    return title
  };

  const RememeberMe = () => {
    const { register } = useFormContext();

    return (
      <FormControlLabel
        sx={{
          span: {
            fontSize: "12px",
            color: "text.secondary",
          },
        }}
        color="secondary"
        control={
          <Checkbox size="small" id="rememberMe" {...register("rememberMe")} />
        }
        label="Remember me"
      />
    );
  };

  const Callback = () => {
        const fiefAuth = useFiefAuth();
        const navigate = useNavigate();
        useEffect(() => {
            fiefAuth
                .authCallback(
                    `${window.location.protocol}//${window.location.host}/callback`,
                )
                .then(() => {
                    navigate("/locations");
                });
        }, [fiefAuth, navigate]);

        return <p></p>;
    };

  return (
    (<BrowserRouter>
        <FiefAuthProvider baseURL={'https://fief.newmexicowaterdata.org'}
                          clientId={'buShmB5KqjE5kirVSz9J2g6of5O276OhHBzUcZLpGEA'}>

      {/*<GitHubBanner />*/}
      {/*<ThemeProvider theme={RefineThemes.Blue}>*/}
            <ColorModeContextProvider>
        <CssBaseline />
        <GlobalStyles styles={{ html: { WebkitFontSmoothing: "auto" } }} />
        <RefineSnackbarProvider>
          <DevtoolsProvider>
            <Refine
              authProvider={authProvider}
              // dataProvider={dataProvider("https://api.fake-rest.refine.dev")}
              dataProvider={dataProvider}
              routerProvider={routerProvider}
              notificationProvider={useNotificationProvider}
              resources={resources}
              options={{
                syncWithLocation: true,
                warnWhenUnsavedChanges: true,
                projectId: "wCqQ1f-agx0FN-70pXIr"
              }}
            >
              <Routes>
                  <Route path='/callback'
                         element={<Callback />}
                  />
                <Route
                  element={
                    <Authenticated
                      key="authenticated-routes"
                      fallback={<CatchAllNavigate to="/login" />}
                    >
                      <ThemedLayoutV2
                        Header={()=>(<ThemedHeaderV2 sticky/>)}
                        Sider={ThemedSiderV2}
                        Title={({ collapsed }) => (
                            <ThemedTitleV2
                                // collapsed is a boolean value that indicates whether the <Sidebar> is collapsed or not
                                collapsed={collapsed}
                                // icon={collapsed ? <MySmallIcon /> : <MyLargeIcon />}
                                text="NMBGMR Data Manager"
                            />
                        )}
                      >
                        <Outlet />
                      </ThemedLayoutV2>
                    </Authenticated>
                  }
                >
                  <Route
                    index
                    element={<NavigateToResource resource="posts" />}
                  />

                  <Route path="/wells">
                    <Route index element={<WellList />} />
                    {/*<Route path="create" element={<PostCreate />} />*/}
                    <Route path="edit/:id" element={<WellEdit />} />
                  </Route>
                  <Route path="/locations">
                    <Route index element={<LocationList />} />
                    <Route path="create" element={<LocationCreate />} />
                    <Route path="edit/:id" element={<LocationEdit />} />
                  </Route>
                    <Route path="/lu_measurement_method">
                        <Route index element={<LookupTableList />} />
                    </Route>
                    <Route path="/lu_level_status">
                        <Route index element={<LookupTableList />} />
                    </Route>
                    <Route path="/lu_data_quality">
                        <Route index element={<LookupTableList />} />
                    </Route>
                    <Route path="/lu_measuring_agency">
                        <Route index element={<LookupTableList />} />
                    </Route>
                    <Route path="/lu_data_source">
                        <Route index element={<LookupTableList />} />
                    </Route>
                </Route>

                <Route
                  element={
                    <Authenticated key="auth-pages" fallback={<Outlet />}>
                      <NavigateToResource resource="posts" />
                    </Authenticated>
                  }
                >
                  <Route
                    path="/login"
                    element={
                      <AuthPage
                        type="login"
                        rememberMe={<RememeberMe />}
                        // formProps={{
                        //   defaultValues: {
                        //     ...authCredentials,
                        //   },
                        // }}
                        providers={[
                            {
                                name: "fief",
                                label: "Sign in with Fief",
                                // icon: (
                                //     <GoogleIcon
                                //         style={{
                                //             fontSize: 24,
                                //         }}
                                //     />
                                // ),
                            },
                          // {
                          //   name: "google",
                          //   label: "Sign in with Google",
                          //   icon: (
                          //     <GoogleIcon
                          //       style={{
                          //         fontSize: 24,
                          //       }}
                          //     />
                          //   ),
                          // },
                          // {
                          //   name: "github",
                          //   label: "Sign in with GitHub",
                          //   icon: (
                          //     <GitHubIcon
                          //       style={{
                          //         fontSize: 24,
                          //       }}
                          //     />
                          //   ),
                          // },
                        ]}
                      />
                    }
                  />
                  <Route
                    path="/register"
                    element={
                      <AuthPage
                        type="register"
                        providers={[
                          {
                            name: "google",
                            label: "Sign in with Google",
                            icon: (
                              <GoogleIcon
                                style={{
                                  fontSize: 24,
                                }}
                              />
                            ),
                          },
                          {
                            name: "github",
                            label: "Sign in with GitHub",
                            icon: (
                              <GitHubIcon
                                style={{
                                  fontSize: 24,
                                }}
                              />
                            ),
                          },
                        ]}
                      />
                    }
                  />
                  <Route
                    path="/forgot-password"
                    element={<AuthPage type="forgotPassword" />}
                  />
                  <Route
                    path="/update-password"
                    element={<AuthPage type="updatePassword" />}
                  />
                </Route>

                <Route
                  element={
                    <Authenticated key="catch-all">
                      <ThemedLayoutV2>
                        <Outlet />
                      </ThemedLayoutV2>
                    </Authenticated>
                  }
                >
                  <Route path="*" element={<ErrorComponent />} />
                </Route>
              </Routes>
              <UnsavedChangesNotifier />
              <DocumentTitleHandler  handler={customTitleHandler}/>
            </Refine>
            <DevtoolsPanel />
          </DevtoolsProvider>
        </RefineSnackbarProvider>
            </ColorModeContextProvider>
        </FiefAuthProvider>
    </BrowserRouter>)
  );
};

export default App;
