// ===============================================================================
// Copyright 2024 Jake Ross
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ===============================================================================
import {Authenticated, Refine} from "@refinedev/core";
import {AuthPage, ErrorComponent, RefineSnackbarProvider, useNotificationProvider,} from "@refinedev/mui";

import routerProvider, {
    CatchAllNavigate,
    DocumentTitleHandler, NavigateToResource,
    UnsavedChangesNotifier,
} from "@refinedev/react-router-v6";
import {BrowserRouter, Navigate, Outlet, Route, Routes,} from "react-router-dom";

import CssBaseline from "@mui/material/CssBaseline";
import GlobalStyles from "@mui/material/GlobalStyles";
import GitHubIcon from "@mui/icons-material/GitHub";
import GoogleIcon from "@mui/icons-material/Google";

import {FiefAuthProvider} from "@fief/fief/react";

import {ampDataProvider} from "@/providers/amp-data-provider";
import {authProvider, fiefConstants} from "@/providers/fief-provider";

import {ThemedLayoutV2} from "@/components/layout";
import {ThemedHeaderV2} from "@/components/layout/header";
import {ThemedSiderV2} from "@/components/layout/sider";
import {ThemedTitleV2} from "@/components/layout/title";

import {resources} from "@/resources";
import {ColorModeContextProvider} from "@/contexts";
import {Home} from "@/pages/home";

import {ProjectCreate, ProjectList, ProjectShow} from "@/pages/geochronology/projects";
import {geochronologyDataProvider} from "@/providers/geochronology-data-provider";
import {SampleCreate, SampleList, SampleShow} from "@/pages/geochronology/samples";
import {MaterialCreate, MaterialList, MaterialShow} from "@/pages/geochronology/materials";

import {
    PrincipalInvestigatorCreate,
    PrincipalInvestigatorList,
    PrincipalInvestigatorShow
} from "@/pages/geochronology/principal_investigators";
import {GeochronologyDashboard} from "@/pages/geochronology/dashboard";
import {GeothermalDashboard} from "@/pages/geothermal/dashboard";
import {CriticalMineralsDashboard} from "@/pages/criticalminerals/dashboard";
import {geothermalDataProvider} from "@/providers/geothermal-data-provider";
import {GeoThermalWellList, GeoThermalWellShow} from "@/pages/geothermal/wells";
import {settings} from "@/settings";
import {Callback, RememberMe} from "@/components/Auth";
import {makeAMPRoutes} from "@/routes/amp";


const App: React.FC = () => {
    const customTitleHandler = ({
                                    resource,
                                    action,
                                    params,
                                    pathname,
                                    autoGeneratedTitle,
                                }) => {
        let title = "NMBGMR Data Manager";
        if (action === "list") {
            title = `${resource.label} | ${title}`;
        }
        return title;
    };

    return (
        <BrowserRouter basename={settings.urlprefix}>
            <ColorModeContextProvider>
                <CssBaseline/>
                <GlobalStyles styles={{html: {WebkitFontSmoothing: "auto"}}}/>
                <RefineSnackbarProvider>
                    <Refine
                        // accessControlProvider={accessControlProvider}
                        authProvider={authProvider}
                        dataProvider={{
                            default: ampDataProvider,
                            amp: ampDataProvider,
                            geochronology: geochronologyDataProvider,
                            geothermal: geothermalDataProvider
                        }}
                        routerProvider={routerProvider}
                        notificationProvider={useNotificationProvider}
                        resources={resources}
                        options={{
                            disableTelemetry: true,
                            syncWithLocation: true,
                            warnWhenUnsavedChanges: true,
                            projectId: "wCqQ1f-agx0FN-70pXIr",
                        }}
                    >
                        <UnsavedChangesNotifier/>
                        <DocumentTitleHandler handler={customTitleHandler}/>

                        <FiefAuthProvider
                            baseURL={fiefConstants.baseURL}
                            clientId={fiefConstants.clientId}
                        >
                            <Routes>
                                <Route
                                element={<Authenticated key={'auth-pages'} fallback={<Outlet/>}
                                                        v3LegacyAuthProviderCompatible={true}>
                                            <Navigate to="/home"/>
                                        </Authenticated>
                                }>
                                    <Route path="/callback" element={<Callback/>}/>
                                    <Route
                                        path="/login"
                                        element={
                                            <AuthPage
                                                type="login"
                                                rememberMe={<RememberMe/>}
                                                providers={[{name: "fief",
                                                        label: "Sign in with Fief"},]}
                                            />
                                        }
                                    />
                                </Route>
                                <Route
                                    element={
                                        <Authenticated
                                            key="authenticated-routes"
                                            redirectOnFail={"/login"}
                                            // fallback={<CatchAllNavigate to="/login"/>}
                                            v3LegacyAuthProviderCompatible={true}
                                        >
                                            <ThemedLayoutV2
                                                Header={() => <ThemedHeaderV2 sticky/>}
                                                Sider={ThemedSiderV2}
                                                Title={({collapsed}) => (
                                                    <ThemedTitleV2
                                                        // collapsed is a boolean value that indicates whether the <Sidebar> is collapsed or not
                                                        collapsed={collapsed}
                                                        // icon={collapsed ? <MySmallIcon /> : <MyLargeIcon />}
                                                        text="NMBGMR Data Manager"
                                                    />
                                                )}
                                            >
                                                <Outlet/>
                                            </ThemedLayoutV2>
                                        </Authenticated>
                                    }
                                >
                                    <Route index element={<Home/>}/>
                                    <Route path={'/home'} element={<Home/>}/>

                                    // amp routes
                                    {makeAMPRoutes()}

                                    // geochronology routes
                                    <Route path="/geochronology">
                                        <Route path="dashboard" element={<GeochronologyDashboard/>}/>
                                        <Route path="principal_investigators">
                                            <Route index element={<PrincipalInvestigatorList/>}/>
                                            <Route path="create" element={<PrincipalInvestigatorCreate/>}/>
                                            {/*<Route path="edit/:id" element={<LocationEdit/>}/>*/}
                                            <Route path="show/:id" element={<PrincipalInvestigatorShow/>}/>
                                        </Route>
                                        <Route path="projects">
                                            <Route index element={<ProjectList/>}/>
                                            <Route path="create" element={<ProjectCreate/>}/>
                                            {/*<Route path="edit/:id" element={<ProjectEdit/>}/>*/}
                                            <Route path="show/:id" element={<ProjectShow/>}/>
                                        </Route>
                                        <Route path="samples">
                                            <Route index element={<SampleList/>}/>
                                            <Route path="create" element={<SampleCreate/>}/>
                                            {/*    <Route path="edit/:id" element={<SampleEdit/>}/>*/}
                                            <Route path="show/:id" element={<SampleShow/>}/>
                                        </Route>
                                        <Route path='materials'>
                                            <Route index element={<MaterialList/>}/>
                                            <Route path="create" element={<MaterialCreate/>}/>
                                            {/*<Route path="edit/:id" element={<MaterialEdit/>}/>*/}
                                            <Route path="show/:id" element={<MaterialShow/>}/>
                                        </Route>
                                    </Route>

                                    // criticalminerals routes
                                    <Route path='/criticalminerals'>
                                        <Route path="dashboard" element={<CriticalMineralsDashboard/>}/>
                                    </Route>

                                    // geothermal routes
                                    <Route path='/geothermal'>
                                        <Route path="dashboard" element={<GeothermalDashboard/>}/>
                                        <Route path="wells">
                                            <Route index element={<GeoThermalWellList/>}/>
                                            {/*<Route path="create" element={<GeoThermalCreate/>}/>*/}
                                            {/*    <Route path="edit/:id" element={<SampleEdit/>}/>*/}
                                            <Route path="show/:id" element={<GeoThermalWellShow/>}/>
                                        </Route>
                                    </Route>
                                </Route>

                                {/*<Route*/}
                                {/*    // element={*/}
                                {/*    //   <Authenticated key="auth-pages" fallback={<Outlet />}>*/}
                                {/*    //     <NavigateToResource resource="Water" />*/}
                                {/*    //   </Authenticated>*/}
                                {/*    // }*/}
                                {/*>*/}
                                {/*    <Route*/}
                                {/*        path="/login"*/}
                                {/*        element={*/}
                                {/*            <AuthPage*/}
                                {/*                type="login"*/}
                                {/*                rememberMe={<RememberMe/>}*/}
                                {/*                // formProps={{*/}
                                {/*                //   defaultValues: {*/}
                                {/*                //     ...authCredentials,*/}
                                {/*                //   },*/}
                                {/*                // }}*/}
                                {/*                providers={[*/}
                                {/*                    {*/}
                                {/*                        name: "fief",*/}
                                {/*                        label: "Sign in with Fief",*/}
                                {/*                        // icon: (*/}
                                {/*                        //     <GoogleIcon*/}
                                {/*                        //         style={{*/}
                                {/*                        //             fontSize: 24,*/}
                                {/*                        //         }}*/}
                                {/*                        //     />*/}
                                {/*                        // ),*/}
                                {/*                    },*/}
                                {/*                    // {*/}
                                {/*                    //   name: "google",*/}
                                {/*                    //   label: "Sign in with Google",*/}
                                {/*                    //   icon: (*/}
                                {/*                    //     <GoogleIcon*/}
                                {/*                    //       style={{*/}
                                {/*                    //         fontSize: 24,*/}
                                {/*                    //       }}*/}
                                {/*                    //     />*/}
                                {/*                    //   ),*/}
                                {/*                    // },*/}
                                {/*                    // {*/}
                                {/*                    //   name: "github",*/}
                                {/*                    //   label: "Sign in with GitHub",*/}
                                {/*                    //   icon: (*/}
                                {/*                    //     <GitHubIcon*/}
                                {/*                    //       style={{*/}
                                {/*                    //         fontSize: 24,*/}
                                {/*                    //       }}*/}
                                {/*                    //     />*/}
                                {/*                    //   ),*/}
                                {/*                    // },*/}
                                {/*                ]}*/}
                                {/*            />*/}
                                {/*        }*/}
                                {/*    />*/}
                                {/*    <Route*/}
                                {/*        path="/register"*/}
                                {/*        element={*/}
                                {/*            <AuthPage*/}
                                {/*                type="register"*/}
                                {/*                providers={[*/}
                                {/*                    {*/}
                                {/*                        name: "google",*/}
                                {/*                        label: "Sign in with Google",*/}
                                {/*                        icon: (*/}
                                {/*                            <GoogleIcon*/}
                                {/*                                style={{*/}
                                {/*                                    fontSize: 24,*/}
                                {/*                                }}*/}
                                {/*                            />*/}
                                {/*                        ),*/}
                                {/*                    },*/}
                                {/*                    {*/}
                                {/*                        name: "github",*/}
                                {/*                        label: "Sign in with GitHub",*/}
                                {/*                        icon: (*/}
                                {/*                            <GitHubIcon*/}
                                {/*                                style={{*/}
                                {/*                                    fontSize: 24,*/}
                                {/*                                }}*/}
                                {/*                            />*/}
                                {/*                        ),*/}
                                {/*                    },*/}
                                {/*                ]}*/}
                                {/*            />*/}
                                {/*        }*/}
                                {/*    />*/}
                                {/*    <Route*/}
                                {/*        path="/forgot-password"*/}
                                {/*        element={<AuthPage type="forgotPassword"/>}*/}
                                {/*    />*/}
                                {/*    <Route*/}
                                {/*        path="/update-password"*/}
                                {/*        element={<AuthPage type="updatePassword"/>}*/}
                                {/*    />*/}
                                {/*</Route>*/}

                                <Route
                                    element={
                                        <Authenticated
                                            v3LegacyAuthProviderCompatible={true}
                                            key="catch-all">
                                            <ThemedLayoutV2>
                                                <Outlet/>
                                            </ThemedLayoutV2>
                                        </Authenticated>
                                    }
                                >
                                    <Route path="*" element={<ErrorComponent/>}/>
                                </Route>
                            </Routes>
                        </FiefAuthProvider>

                    </Refine>
                </RefineSnackbarProvider>
            </ColorModeContextProvider>
        </BrowserRouter>
    );
};

export default App;
// ============= EOF =============================================
