import { CssBaseline, GlobalStyles } from '@mui/material'
import { LocalizationProvider } from '@mui/x-date-pickers'
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'
import { Action, IResourceItem, Refine } from '@refinedev/core'
import { RefineSnackbarProvider, useNotificationProvider } from '@refinedev/mui'
import routerProvider, {
  DocumentTitleHandler,
  UnsavedChangesNotifier,
} from '@refinedev/react-router'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ReactNode } from 'react'
import { AppBreadcrumb } from '@/components/AppBreadcrumb'
import { CopyPasteTracking } from '@/components/analytics/CopyPasteTracking'
import { ErrorBoundary } from '@/components/analytics/ErrorBoundary'
import { PostHogIdentify } from '@/components/analytics/PostHogIdentify'
import { PostHogPageview } from '@/components/analytics/PostHogPageview'
import { TooltipProvider } from '@/components/ui/tooltip'
import { ColorModeContextProvider } from '@/contexts'
import {
  accessControlProvider,
  ampDataProvider,
  authentikAuthProvider,
  geochronologyDataProvider,
  geothermalDataProvider,
  ocotilloDataProvider,
  ogcapiDataProvider,
  ogcapiInternalDataProvider,
  st2DataProvider,
  usgsNwisOgcapiDataProvider,
} from '@/providers'
import { SearchProvider } from '@/providers/search-provider'
import { resources } from '@/resources'

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
    },
  },
})
const appTitle = import.meta.env.DEV
  ? 'Ocotillo (Dev)'
  : import.meta.env.VITE_APP_TITLE || 'Ocotillo'

const ACTION_LABELS: Partial<Record<Action, string>> = {
  create: 'New',
  edit: 'Edit',
  clone: 'Clone',
}

const customTitleHandler = ({
  resource,
  action,
}: {
  resource?: IResourceItem
  action?: Action
  params?: Record<string, string | undefined>
  pathname?: string
  autoGeneratedTitle: string
}) => {
  if (!resource?.meta?.label) return appTitle
  const resourceLabel = resource.meta.label
  const actionLabel = action ? ACTION_LABELS[action] : undefined
  // specificity-first: "New - Wells | Ocotillo"
  // show pages get their title replaced by the record name once data loads
  return actionLabel
    ? `${actionLabel} - ${resourceLabel} | ${appTitle}`
    : `${resourceLabel} | ${appTitle}`
}

export const AppProviders = ({ children }: { children: ReactNode }) => (
  <ColorModeContextProvider>
    <TooltipProvider>
      <CssBaseline />
      <GlobalStyles styles={{ html: { WebkitFontSmoothing: 'auto' } }} />
      <RefineSnackbarProvider>
        <Refine
          authProvider={authentikAuthProvider}
          dataProvider={{
            default: ocotilloDataProvider,
            amp: ampDataProvider,
            geochronology: geochronologyDataProvider,
            geothermal: geothermalDataProvider,
            ogcapi: ogcapiDataProvider,
            'ogcapi-internal': ogcapiInternalDataProvider,
            'usgs-nwis-ogcapi': usgsNwisOgcapiDataProvider,
            st2: st2DataProvider,
            ocotillo: ocotilloDataProvider,
          }}
          accessControlProvider={accessControlProvider}
          routerProvider={routerProvider}
          notificationProvider={useNotificationProvider}
          resources={resources}
          options={{
            disableTelemetry: true,
            syncWithLocation: false, // Prevents Refine from writing filter/sort/pagination state into URL query params. Navigation URLs (/well/show/123) are unaffected -- those are managed by React Router.
            warnWhenUnsavedChanges: true,
            projectId: import.meta.env.VITE_REFINE_PROJECT_ID,
            breadcrumb: <AppBreadcrumb />,
          }}
        >
          <UnsavedChangesNotifier />
          <PostHogPageview />
          <PostHogIdentify />
          <CopyPasteTracking />
          <DocumentTitleHandler handler={customTitleHandler} />
          <LocalizationProvider dateAdapter={AdapterDayjs}>
            <SearchProvider>
              <QueryClientProvider client={queryClient}>
                <ErrorBoundary name="App">{children}</ErrorBoundary>
              </QueryClientProvider>
            </SearchProvider>
          </LocalizationProvider>
        </Refine>
      </RefineSnackbarProvider>
    </TooltipProvider>
  </ColorModeContextProvider>
)
