import { ReactNode } from 'react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import {
  Breadcrumb,
  RefineSnackbarProvider,
  useNotificationProvider,
} from '@refinedev/mui'
import { DevtoolsProvider, DevtoolsPanel } from '@refinedev/devtools'
import { LocalizationProvider } from '@mui/x-date-pickers'
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'
import { CssBaseline, GlobalStyles } from '@mui/material'
import { Action, IResourceItem, Refine } from '@refinedev/core'
import routerProvider, {
  DocumentTitleHandler,
  UnsavedChangesNotifier,
} from '@refinedev/react-router-v6'
import { ColorModeContextProvider } from '@/contexts'
import {
  ampDataProvider,
  authentikAuthProvider,
  ocotilloDataProvider,
  accessControlProvider,
  st2DataProvider,
  geothermalDataProvider,
  geochronologyDataProvider,
  ogcapiDataProvider,
} from '@/providers'
import { resources } from '@/resources'

const queryClient = new QueryClient()

const customTitleHandler = (options: {
  resource?: IResourceItem
  action?: Action
  params?: Record<string, string | undefined>
  pathname?: string
  autoGeneratedTitle: string
}) =>
  options.action === 'list'
    ? `${options.resource.meta.label} | ${import.meta.env.VITE_APP_TITLE || 'NMBGMR Ocotillo'}`
    : `${import.meta.env.VITE_APP_TITLE || 'NMBGMR Ocotillo'}`

export const AppProviders = ({ children }: { children: ReactNode }) => (
  <ColorModeContextProvider>
    <CssBaseline />
    <GlobalStyles styles={{ html: { WebkitFontSmoothing: 'auto' } }} />
    <RefineSnackbarProvider>
      <DevtoolsProvider>
        <Refine
          authProvider={authentikAuthProvider}
          dataProvider={{
            default: ocotilloDataProvider,
            amp: ampDataProvider,
            geochronology: geochronologyDataProvider,
            geothermal: geothermalDataProvider,
            ogcapi: ogcapiDataProvider,
            st2: st2DataProvider,
            ocotillo: ocotilloDataProvider,
          }}
          accessControlProvider={accessControlProvider}
          routerProvider={routerProvider}
          notificationProvider={useNotificationProvider}
          resources={resources}
          options={{
            disableTelemetry: true,
            syncWithLocation: true,
            warnWhenUnsavedChanges: true,
            projectId: import.meta.env.VITE_REFINE_PROJECT_ID,
            breadcrumb: <Breadcrumb hideIcons />,
          }}
        >
          <UnsavedChangesNotifier />
          <DocumentTitleHandler handler={customTitleHandler} />
          <LocalizationProvider dateAdapter={AdapterDayjs}>
            <QueryClientProvider client={queryClient}>
              {children}
            </QueryClientProvider>
          </LocalizationProvider>
        </Refine>
        <DevtoolsPanel />
      </DevtoolsProvider>
    </RefineSnackbarProvider>
  </ColorModeContextProvider>
)
