import { ReactNode } from 'react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { RefineSnackbarProvider, useNotificationProvider } from '@refinedev/mui'
import { AppBreadcrumb } from '@/components/AppBreadcrumb'
import { DevtoolsProvider, DevtoolsPanel } from '@refinedev/devtools'
import { LocalizationProvider } from '@mui/x-date-pickers'
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'
import { CssBaseline, GlobalStyles } from '@mui/material'
import { Action, IResourceItem, Refine } from '@refinedev/core'
import routerProvider, {
  DocumentTitleHandler,
  UnsavedChangesNotifier,
} from '@refinedev/react-router'
import { ColorModeContextProvider } from '@/contexts'
import {
  ampDataProvider,
  authentikAuthProvider,
  ocotilloDataProvider,
  accessControlProvider,
  st2DataProvider,
  geothermalDataProvider,
  geochronologyDataProvider,
  ogcapiDataProvider,
  usgsNwisOgcapiDataProvider,
} from '@/providers'
import { resources } from '@/resources'
import { PostHogPageview } from '@/components/analytics/PostHogPageview'
import { PostHogIdentify } from '@/components/analytics/PostHogIdentify'
import { ErrorBoundary } from '@/components/analytics/ErrorBoundary'
import { SearchProvider } from '@/providers/search-provider'

const queryClient = new QueryClient()
const appTitle = import.meta.env.DEV
  ? 'Ocotillo (Dev)'
  : import.meta.env.VITE_APP_TITLE || 'Ocotillo'

const ACTION_LABELS: Partial<Record<Action, string>> = {
  create: 'New',
  edit: 'Edit',
  clone: 'Clone',
}

const customTitleHandler = ({
  resource,
  action,
}: {
  resource?: IResourceItem
  action?: Action
  params?: Record<string, string | undefined>
  pathname?: string
  autoGeneratedTitle: string
}) => {
  if (!resource?.meta?.label) return appTitle
  const resourceLabel = resource.meta.label
  const actionLabel = action ? ACTION_LABELS[action] : undefined
  // specificity-first: "New - Wells | Ocotillo"
  // show pages get their title replaced by the record name once data loads
  return actionLabel
    ? `${actionLabel} - ${resourceLabel} | ${appTitle}`
    : `${resourceLabel} | ${appTitle}`
}

export const AppProviders = ({ children }: { children: ReactNode }) => (
  <ColorModeContextProvider>
    <CssBaseline />
    <GlobalStyles styles={{ html: { WebkitFontSmoothing: 'auto' } }} />
    <RefineSnackbarProvider>
      <DevtoolsProvider>
        <Refine
          authProvider={authentikAuthProvider}
          dataProvider={{
            default: ocotilloDataProvider,
            amp: ampDataProvider,
            geochronology: geochronologyDataProvider,
            geothermal: geothermalDataProvider,
            ogcapi: ogcapiDataProvider,
            'usgs-nwis-ogcapi': usgsNwisOgcapiDataProvider,
            st2: st2DataProvider,
            ocotillo: ocotilloDataProvider,
          }}
          accessControlProvider={accessControlProvider}
          routerProvider={routerProvider}
          notificationProvider={useNotificationProvider}
          resources={resources}
          options={{
            disableTelemetry: true,
            syncWithLocation: false, // Prevents Refine from writing filter/sort/pagination state into URL query params. Navigation URLs (/well/show/123) are unaffected -- those are managed by React Router.
            warnWhenUnsavedChanges: true,
            projectId: import.meta.env.VITE_REFINE_PROJECT_ID,
            breadcrumb: <AppBreadcrumb />,
          }}
        >
          <UnsavedChangesNotifier />
          <PostHogPageview />
          <PostHogIdentify />
          <DocumentTitleHandler handler={customTitleHandler} />
          <LocalizationProvider dateAdapter={AdapterDayjs}>
            <SearchProvider>
              <QueryClientProvider client={queryClient}>
                <ErrorBoundary name="App">
                  {children}
                </ErrorBoundary>
              </QueryClientProvider>
            </SearchProvider>
          </LocalizationProvider>
        </Refine>
        <DevtoolsPanel />
      </DevtoolsProvider>
    </RefineSnackbarProvider>
  </ColorModeContextProvider>
)
