name: CD deploy staging to GAE

on:
  push:
    branches: [ staging ]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      # checkout the repo
      - uses: actions/checkout@v4

      #build ocotillo
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install deps & build
        env:
          VITE_APP_TITLE: "NMBGMR Ocotillo"
          VITE_MAPBOX_TOKEN: ${{ secrets.VITE_MAPBOX_TOKEN }}
          VITE_BASE_URL: '/'
          VITE_AUTHENTIK_CLIENT_ID: ${{ vars.VITE_AUTHENTIK_CLIENT_ID }}
          VITE_AUTHENTIK_URL: ${{ vars.VITE_AUTHENTIK_URL }}
          VITE_AUTHENTIK_REDIRECT_URI: ${{ vars.VITE_AUTHENTIK_REDIRECT_URI }}
          VITE_OCOTILLO_API_URL: ${{ vars.VITE_OCOTILLO_API_URL }}

        run: |
          npm ci
          npm audit fix || true
          npm run build

      # authenticate to Google Cloud
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # deploy to App Engine
      - id: deploy
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: app.yaml
          promote: true

      #      # Clean up old versions - delete only the oldest version, one created and one destroyed
      #      - name: Clean up oldest version
      #        run: |
      #          OLDEST_VERSION=$(gcloud app versions list --service=ocotillo-staging --project=${{ secrets.GCP_PROJECT_ID }} --format="value(id)" --sort-by="version.createTime" | head -n 1)
      #          if [ ! -z "$OLDEST_VERSION" ]; then
      #            echo "Deleting oldest version: $OLDEST_VERSION"
      #            gcloud app versions delete $OLDEST_VERSION --service=ocotillo-staging --project=${{ secrets.GCP_PROJECT_ID }} --quiet
      #              echo "Deleted oldest version: $OLDEST_VERSION"
      #            else
      #              echo "No versions to delete"
      #            fi

      # Use PR author's username as git user name
      - name: Set up git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Tag commit
        run: |
          git tag -a "ocotillodev-deploy-$(date -u +%Y-%m-%d)T$(date -u +%H-%M-%S%z)" -m "ocotillodev deployment: $
          (date -u +%Y-%m-%d)T$(date -u +%H:%M:%S%z)"
          git push origin --tags